
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace INGServer.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Account
{

    public int id_account { get; set; }

    public int id_user { get; set; }

    public string name { get; set; }

    public decimal balance { get; set; }

}

}
