
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace INGServer.Models
{

using System;
    using System.Collections.Generic;
    
public partial class FavouritePayment
{

    public int id_payment { get; set; }

    public int id_account { get; set; }

    public int id_reciever { get; set; }

    public decimal amount { get; set; }

    public string name { get; set; }

}

}
